### ISSUE TITLE
`jjjpn_operator_test` does not compile

### ISSUE THREAD

**Issue by kc9jud** [nd-nuclear-theory/basis#2]
This function does not compile:

https://github.com/nd-nuclear-theory/basis/blob/3e15b3c420ecffc246d487c04c420621ffb73ac5/test/jjjpn_operator_test.cpp#L19-L49

Error:
```
> cmake --build build-debug/ -- jjjpn_operator_test
[ 88%] Built target basis
[ 94%] Building CXX object CMakeFiles/jjjpn_operator_test.dir/test/jjjpn_operator_test.cpp.o
test/jjjpn_operator_test.cpp: In function ‘void CanonicalizationTest(const string&)’:
test/jjjpn_operator_test.cpp:29:7: error: ‘orbital_space’ was not declared in this scope
   29 |       orbital_space,
      |       ^~~~~~~~~~~~~
test/jjjpn_operator_test.cpp:30:7: error: ‘weight_max’ was not declared in this scope
   30 |       weight_max,
      |       ^~~~~~~~~~
test/jjjpn_operator_test.cpp:31:7: error: ‘shell’ has not been declared
   31 |       shell::kH2SpaceOrdering.at(run_parameters.output_format)
      |       ^~~~~
test/jjjpn_operator_test.cpp:31:34: error: ‘run_parameters’ was not declared in this scope
   31 |       shell::kH2SpaceOrdering.at(run_parameters.output_format)
      |                                  ^~~~~~~~~~~~~~
test/jjjpn_operator_test.cpp:45:3: error: ‘LookUpStateFromXPNLabels’ was not declared in this scope
   45 |   LookUpStateFromXPNLabels(orbital_space, two_body_space, 1, 1, 0);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
gmake[3]: *** [CMakeFiles/jjjpn_operator_test.dir/build.make:76: CMakeFiles/jjjpn_operator_test.dir/test/jjjpn_operator_test.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:396: CMakeFiles/jjjpn_operator_test.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:403: CMakeFiles/jjjpn_operator_test.dir/rule] Error 2
gmake: *** [Makefile:312: jjjpn_operator_test] Error 2
```

The test seems to have been introduced in commit 9cff12de16b78dfa1c90a40073dfdfa013ef763f. It seems to depend on [`shell`](https://github.com/nd-nuclear-theory/shell), so it probably doesn't belong as a test in `basis`.

**Comment by mark-caprio** [comment]
Resolved with commit 7b493c7ce4456df8d15772e3e012afb058682a28.
